# Generated by Django 5.0 on 2024-06-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_customuser_profile_image_driver_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='phone_number',
        ),
    ]
