# Generated by Django 5.0 on 2024-06-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_driver_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='organization',
        ),
        migrations.AddField(
            model_name='organization',
            name='driver',
            field=models.ManyToManyField(blank=True, related_query_name='organization_driver', to='authentication.driver'),
        ),
    ]
